### ISSUE TITLE
Error on 'service destroy': "error": "DependencyViolation: Network vpc-57e4643f has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.\n\tstatus code: 400, request id: 33995f40-4c81-4b13-b7fc-b60a867c994d"

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#400] opened 2017-04-04 12:41 UTC

**Comment by reidjc** [comment] 2017-04-04 13:44
Re-running the destroy command after the error is successful.

**Comment by purehyperbole** [comment] 2017-04-04 17:00
Issue was caused by missing internet gateway fields on network event. When the network was created, these fields were being discarded, meaning that network was returning a dependency of "internet_gateway::", which was silently failing when calling mapper.LoadGraph(). Fix has been pushed to develop of ernestaws and will require a rebuild of all-all-aws-connector

**Closed by purehyperbole** 2017-04-04 17:00 UTC
Labels: 2.0.0, pre release bug
